export const UPDATE_POINT_COUNT = 'UPDATE_POINT_COUNT';
export const GET_DATA = 'GET_DATA';
export const SET_LOADING = 'SET_LOADING';
export const TOGGLE_SATELLITE_BASEMAP = 'TOGGLE_SATELLITE_BASEMAP';
export const TOGGLE_HEATMAP = 'TOGGLE_HEATMAP';
